#[derive(Copy, Clone, Debug)]
pub enum Logograph {
    A,
    AKESI,
    ALA,
    ALASA,
    ALI,
    ANPA,
    ANTE,
    ANU,
    AWEN,
    E,
    EN,
    ESUN,
    IJO,
    IKE,
    ILO,
    INSA,
    JAKI,
    JAN,
    JELO,
    JO,
    KALA,
    KALAMA,
    KAMA,
    KASI,
    KEN,
    KEPEKEN,
    KILI,
    KIN,
    KIWEN,
    KO,
    KON,
    KULE,
    KULUPU,
    KUTE,
    LA,
    LAPE,
    LASO,
    LAWA,
    LEN,
    LETE,
    LI,
    LILI,
    LINJA,
    LIPU,
    LOJE,
    LON,
    LUKA,
    LUKIN,
    LUPA,
    MA,
    MAMA,
    MANI,
    MELI,
    MI,
    MIJE,
    MOKU,
    MOLI,
    MONSI,
    MU,
    MUN,
    MUSI,
    MUTE,
    NANPA,
    NASA,
    NASIN,
    NENA,
    NI,
    NIMI,
    NOKA,
    O,
    OKO,
    OLIN,
    ONA,
    OPEN,
    PAKALA,
    PALI,
    PALISA,
    PAN,
    PANA,
    PI,
    PILIN,
    PIMEJA,
    PINI,
    PIPI,
    POKA,
    POKI,
    PONA,
    PU,
    SAMA,
    SELI,
    SELO,
    SEME,
    SEWI,
    SIJELO,
    SIKE,
    SIN,
    SINA,
    SINPIN,
    SITELEN,
    SONA,
    SOWELI,
    SULI,
    SUNO,
    SUPA,
    SUWI,
    TAN,
    TASO,
    TAWA,
    TELO,
    TENPO,
    TOKI,
    TOMO,
    TU,
    UNPA,
    UTA,
    UTALA,
    WALO,
    WAN,
    WASO,
    WAWA,
    WEKA,
    WILE,
    APEJA,
    KIPISI,
    LEKO,
    MAJUNA,
    MONSUTA,
    NAMAKO,
    PAKE,
    PATA,
    POWE,
    TONSI,
}

impl Logograph {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "a" => Some(Logograph::A),
            "akesi" => Some(Logograph::AKESI),
            "ala" => Some(Logograph::ALA),
            "alasa" => Some(Logograph::ALASA),
            "ali" => Some(Logograph::ALI),
            "anpa" => Some(Logograph::ANPA),
            "ante" => Some(Logograph::ANTE),
            "anu" => Some(Logograph::ANU),
            "awen" => Some(Logograph::AWEN),
            "e" => Some(Logograph::E),
            "en" => Some(Logograph::EN),
            "esun" => Some(Logograph::ESUN),
            "ijo" => Some(Logograph::IJO),
            "ike" => Some(Logograph::IKE),
            "ilo" => Some(Logograph::ILO),
            "insa" => Some(Logograph::INSA),
            "jaki" => Some(Logograph::JAKI),
            "jan" => Some(Logograph::JAN),
            "jelo" => Some(Logograph::JELO),
            "jo" => Some(Logograph::JO),
            "kala" => Some(Logograph::KALA),
            "kalama" => Some(Logograph::KALAMA),
            "kama" => Some(Logograph::KAMA),
            "kasi" => Some(Logograph::KASI),
            "ken" => Some(Logograph::KEN),
            "kepeken" => Some(Logograph::KEPEKEN),
            "kili" => Some(Logograph::KILI),
            "kin" => Some(Logograph::KIN),
            "kiwen" => Some(Logograph::KIWEN),
            "ko" => Some(Logograph::KO),
            "kon" => Some(Logograph::KON),
            "kule" => Some(Logograph::KULE),
            "kulupu" => Some(Logograph::KULUPU),
            "kute" => Some(Logograph::KUTE),
            "la" => Some(Logograph::LA),
            "lape" => Some(Logograph::LAPE),
            "laso" => Some(Logograph::LASO),
            "lawa" => Some(Logograph::LAWA),
            "len" => Some(Logograph::LEN),
            "lete" => Some(Logograph::LETE),
            "li" => Some(Logograph::LI),
            "lili" => Some(Logograph::LILI),
            "linja" => Some(Logograph::LINJA),
            "lipu" => Some(Logograph::LIPU),
            "loje" => Some(Logograph::LOJE),
            "lon" => Some(Logograph::LON),
            "luka" => Some(Logograph::LUKA),
            "lukin" => Some(Logograph::LUKIN),
            "lupa" => Some(Logograph::LUPA),
            "ma" => Some(Logograph::MA),
            "mama" => Some(Logograph::MAMA),
            "mani" => Some(Logograph::MANI),
            "meli" => Some(Logograph::MELI),
            "mi" => Some(Logograph::MI),
            "mije" => Some(Logograph::MIJE),
            "moku" => Some(Logograph::MOKU),
            "moli" => Some(Logograph::MOLI),
            "monsi" => Some(Logograph::MONSI),
            "mu" => Some(Logograph::MU),
            "mun" => Some(Logograph::MUN),
            "musi" => Some(Logograph::MUSI),
            "mute" => Some(Logograph::MUTE),
            "nanpa" => Some(Logograph::NANPA),
            "nasa" => Some(Logograph::NASA),
            "nasin" => Some(Logograph::NASIN),
            "nena" => Some(Logograph::NENA),
            "ni" => Some(Logograph::NI),
            "nimi" => Some(Logograph::NIMI),
            "noka" => Some(Logograph::NOKA),
            "o" => Some(Logograph::O),
            "oko" => Some(Logograph::OKO),
            "olin" => Some(Logograph::OLIN),
            "ona" => Some(Logograph::ONA),
            "open" => Some(Logograph::OPEN),
            "pakala" => Some(Logograph::PAKALA),
            "pali" => Some(Logograph::PALI),
            "palisa" => Some(Logograph::PALISA),
            "pan" => Some(Logograph::PAN),
            "pana" => Some(Logograph::PANA),
            "pi" => Some(Logograph::PI),
            "pilin" => Some(Logograph::PILIN),
            "pimeja" => Some(Logograph::PIMEJA),
            "pini" => Some(Logograph::PINI),
            "pipi" => Some(Logograph::PIPI),
            "poka" => Some(Logograph::POKA),
            "poki" => Some(Logograph::POKI),
            "pona" => Some(Logograph::PONA),
            "pu" => Some(Logograph::PU),
            "sama" => Some(Logograph::SAMA),
            "seli" => Some(Logograph::SELI),
            "selo" => Some(Logograph::SELO),
            "seme" => Some(Logograph::SEME),
            "sewi" => Some(Logograph::SEWI),
            "sijelo" => Some(Logograph::SIJELO),
            "sike" => Some(Logograph::SIKE),
            "sin" => Some(Logograph::SIN),
            "sina" => Some(Logograph::SINA),
            "sinpin" => Some(Logograph::SINPIN),
            "sitelen" => Some(Logograph::SITELEN),
            "sona" => Some(Logograph::SONA),
            "soweli" => Some(Logograph::SOWELI),
            "suli" => Some(Logograph::SULI),
            "suno" => Some(Logograph::SUNO),
            "supa" => Some(Logograph::SUPA),
            "suwi" => Some(Logograph::SUWI),
            "tan" => Some(Logograph::TAN),
            "taso" => Some(Logograph::TASO),
            "tawa" => Some(Logograph::TAWA),
            "telo" => Some(Logograph::TELO),
            "tenpo" => Some(Logograph::TENPO),
            "toki" => Some(Logograph::TOKI),
            "tomo" => Some(Logograph::TOMO),
            "tu" => Some(Logograph::TU),
            "unpa" => Some(Logograph::UNPA),
            "uta" => Some(Logograph::UTA),
            "utala" => Some(Logograph::UTALA),
            "walo" => Some(Logograph::WALO),
            "wan" => Some(Logograph::WAN),
            "waso" => Some(Logograph::WASO),
            "wawa" => Some(Logograph::WAWA),
            "weka" => Some(Logograph::WEKA),
            "wile" => Some(Logograph::WILE),
            "apeja" => Some(Logograph::APEJA),
            "kipisi" => Some(Logograph::KIPISI),
            "leko" => Some(Logograph::LEKO),
            "majuna" => Some(Logograph::MAJUNA),
            "monsuta" => Some(Logograph::MONSUTA),
            "namako" => Some(Logograph::NAMAKO),
            "pake" => Some(Logograph::PAKE),
            "pata" => Some(Logograph::PATA),
            "powe" => Some(Logograph::POWE),
            "tonsi" => Some(Logograph::TONSI),
            _ => None,
        }
    }

    pub fn material_id(&self) -> [u8; 2] {
        const COLUMNS: u8 = 10;
        let val = *self as u8;
        let row = val / COLUMNS;
        let column = val % COLUMNS;
        [column + 6, row]
    }

    pub fn options() -> [&'static str; 132] {
        [
            "a", "akesi", "ala", "alasa", "ali", "anpa", "ante", "anu", "awen", "e",
            "en", "esun", "ijo", "ike", "ilo", "insa", "jaki", "jan", "jelo", "jo",
            "kala", "kalama", "kama", "kasi", "ken", "kepeken", "kili", "kin", "kiwen",
            "ko", "kon", "kule", "kulupu", "kute", "la", "lape", "laso", "lawa", "len",
            "lete", "li", "lili", "linja", "lipu", "loje", "lon", "luka", "lukin",
            "lupa", "ma", "mama", "mani", "meli", "mi", "mije", "moku", "moli",
            "monsi", "mu", "mun", "musi", "mute", "nanpa", "nasa", "nasin", "nena",
            "ni", "nimi", "noka", "o", "oko", "olin", "ona", "open", "pakala", "pali",
            "palisa", "pan", "pana", "pi", "pilin", "pimeja", "pini", "pipi", "poka",
            "poki", "pona", "pu", "sama", "seli", "selo", "seme", "sewi", "sijelo",
            "sike", "sin", "sina", "sinpin", "sitelen", "sona", "soweli", "suli",
            "suno", "supa", "suwi", "tan", "taso", "tawa", "telo", "tenpo", "toki",
            "tomo", "tu", "unpa", "uta", "utala", "walo", "wan", "waso", "wawa",
            "weka", "wile", "apeja", "kipisi", "leko", "majuna", "monsuta", "namako",
            "pake", "pata", "powe", "tonsi",
        ]
    }
}
